---
- hosts: all
  become: true
  vars: 
    ssh_use_pam: true
    jenkins_hostname: 54.74.130.7
    ansible_remote_tmp: /tmp/ansible
    PubkeyAcceptedAlgorithms: +ssh-rsa
    HostkeyAlgorithms: +ssh-rsa
  tasks:
    - name: Create user account
      ansible.builtin.user:
        name: kula
        comment: Thulani Kula
        uid: 1040
        group: admin

      
